### ISSUE TITLE
Fix periodic fetching

### ISSUE THREAD

**Issue by InputUsername** [RUGSoftEng/2018-PyDash.io#136] opened 2018-04-14 14:34 UTC
As of right now, there is a bug in the periodic fetching system. Historical data is retrieved correctly while seeding the database, but subsequent updates (executed in periodic tasks) don't seem to happen.

- only two periodic task executions appear to happen;
- these seemingly only happen once;
- and they don't do anything at all.

This leads me to believe that there's a bug in the task scheduler, but I can't confirm this.

**Comment by TWEApol** [comment] 2018-04-14 14:54
It seems that the periodic task executions that appear to happen, have the same dashboard_id. This might be related to flask running the __init__.py file twice in debug mode.

**Comment by TWEApol** [comment] 2018-04-14 15:57
After some testing, I assume the `find_dashboard(dashboard_id)` call in `_update_endpoint_calls_task(dashboard_id)` in `/pydash_app/fetching/dashboard_fetch.py`, for some yet unknown reason.

**Comment by TheVeggydude** [comment] 2018-04-14 20:35
Confirmed what @TWEApol suggested. `database_root.dashboards['id', dashboard_id]` does not find a dashboard and locks up. @InputUsername and I believe this to be the task thread not being able to contact ZOE and lock up because of it.

**Comment by Qqwy** [comment] 2018-04-15 04:39
Idea to try: Set up the database connection (See `pydash_app/impl/database.py`) inside the function we're calling (i.e. `find_dashboard`) to see if the problem is that the connection was set up at module-inclusion time (maybe this interferes with the task-splitting over subprocesses or something?)

**Comment by Qqwy** [comment] 2018-04-21 15:07
Can you guys create a simple reproducible example so I can try to figure out what the problem is?

**Comment by InputUsername** [comment] 2018-04-21 17:07
Yes, I will get on this

**Comment by InputUsername** [comment] 2018-04-22 15:14
@Qqwy I've set up some code in `backend/periodic_fetching` that adds a dashboard to your (and my) user on seeding, and creates a periodic task for the dashboards when running the app. Right now, only one task is run, and it hangs during that run.

**Comment by Qqwy** [comment] 2018-04-23 21:49
Should be fixed now; `database_root()` now is a function that caches the database connection. A new connection is only made if there was no connection made yet _from this OS process_. (That last part is why it now works!)

Please check to make sure it also works on your end! ;-)

**Closed** 2018-04-28 15:48 UTC
Labels: back-end, bug, help wanted
