### ISSUE TITLE
Bug: /api/dashboards returns duplicate data

### ISSUE THREAD

**Issue by ArjanTilstra** [RUGSoftEng/2018-PyDash.io#106] opened 2018-04-02 12:40 UTC
From what I've been able to read from the backend code, the endpoint currently returns mockdata containing details about 2 dashboards for every dashboard found for the current user. This results in duplicate data being returned.

**Comment by Qqwy** [comment] 2018-04-02 13:42
This went wrong; probably caused by a merge that 'automatically worked' but with the merged version no longer working as intended.

**Closed** 2018-04-02 13:55 UTC
Labels: back-end, bug
